### ISSUE TITLE
Ingame DND message not saved

### ISSUE THREAD

**Issue by AstroxV** [Exslims/MercuryTrade#129]
When setting a response text for ingame DND it is not saved. It will always use "Response Text" as DND message.

**Comment by Exslims** [comment]
not saved after restarting mercury or always?

**Comment by AstroxV** [comment]
Always, when changint the message and hitting the save button and then try to go DND ingame it shows the "Response Text", and when restarting Mercury, its back in the settings on "Response Text".

**Comment by AstroxV** [comment]
This is in the latest version btw, 1.0.1.8.1. I just noticed the warning of the 1.0.1.8+ versions having many bugs, but still so you know.

**Comment by Exslims** [comment]
fixed in 1.0.1.9

**Comment by AstroxV** [comment]
Sorry to let you know, it's not fixed :(
The message is not saved when I change it in the settings. It is as long as mercury is running, but when you restart it, it's not saved ad is back to "Response message". When I manually edit the message in configuration.json it shows up properly in the settings after I restart Mercury, and it shows when I hit DND, so it just isn't saved in the file.

**Comment by Exslims** [comment]
okay, I hope this only applies to DND response
